#!/bin/bash

# set -x

# GCC="podman run --rm -v ${PWD}:/work:z rv32-compiler riscv32-unknown-elf-gcc"
GCC=/home/fukuda/opt/gcc/riscv32-unknown-elf-rv32im/bin/riscv32-unknown-elf-gcc
# QEMU="podman run --rm -v ${PWD}:/work:z rv32-compiler qemu-riscv32"
QEMU=qemu-riscv32
TMP_DIR=/tmp

assert() {
  expected="$1"
  input="$2"

  ./fcc "$input" > /tmp/tmp.s
  if [ $? -ne 0 ]; then
    echo "'./fcc $input' failed"
    exit 1
  fi
  $GCC -o ${TMP_DIR}/tmp -g ${TMP_DIR}/tmp.s test/predefined.c
  $QEMU ${TMP_DIR}/tmp
  actual="$?"

  if [ "$actual" = "$expected" ]; then
    echo "$input => $actual"
  else
    echo "$input => $expected expected, but got $actual"
    exit 1
  fi
}



assert 0 "int main() {return 0;}"
assert 100 "int main() {return 100;}"
assert 1 "int main() {return 1;}"
assert 3 "int main() {return 1+2;}"
assert 7 "int main() {return 1+2*3;}"
assert 1 "int main() {return 0 + 1;}"
assert 5 "int main() {return 2 + 3;}"
assert 1 "int main() {return 3 - 2;}"
assert 10 "int main() {return 1 +2+3 - 4   + 5 + 6 - 7 + 8 -9 + 15 - 10;}"
assert 7 "int main() {return 1 + 2*3;}"
assert 62 "int main() {return 4 * 5 + 6 * 7;}"
assert 53 "int main() {return (1 + 2) * 3 + 4 * (5 + 6);}"
assert 0 "int main() {return 0 == 1;}"
assert 1 "int main() {return 10 == 10;}"
assert 1 "int main() {return 0 != 1;}"
assert 0 "int main() {return 10 != 10;}"
assert 1 "int main() {return 1 + 2 == 3;}"
assert 1 "int main() {return 1 + 2 + 3 == 2 * 3;}"
assert 1 "int main() {return 1 < 2;}"
assert 0 "int main() {return 1 < 1;}"
assert 0 "int main() {return 1 < 0;}"
assert 1 "int main() {return 1 + 2 <= 3;}"
assert 0 "int main() {return 1 + 2 < 3;}"
assert 0 "int main() {return 5 > 6;}"
assert 0 "int main() {return 2 + 3 > 2 * 3;}"
assert 1 "int main() {return 7 <= 8;}"
assert 1 "int main() {return 8 <= 8;}"
assert 0 "int main() {return 9 <= 8;}"
assert 1 "int main() {return 8 >= 7;}"
assert 1 "int main() {return 2 * 4 >= 3 + 4;}"
assert 0 "int main() {int a; return a;}"
assert 0 "int main() {int b; return b;}"
assert 0 "int main() {int a; int b; return a + b;}"
assert 1 "int main() {int a; return a = 1;}"
assert 6 "int main() {int a; return a = 1 * 2 + 3 - 4 + 5;}"
assert 3 "int main() {int a; return 1 + (a = 2);}"
assert 3 "int main() {int a; return (a=1) + 2;}"
assert 2 "int main() {int a; return (a=1) + a;}" # 評価順依存？
assert 3 "int main() {int a; int b; return a = b = 1 + 2;}"
assert 2 "int main() {int a; int b; return a = (b = 1) + 1;}"
assert 27 "int main() {int a; int b; return (a = 1) + (b = 2) + (a + 3) * (b + 4);}"
assert 0 "int main() {int abc; return abc = 0;}"
assert 1 "int main() {int abc; return abc = 1;}"
assert 3 "int main() {int abc; return 1 + (abc = 2);}"
assert 5 "int main() {int abc; return 1 + (abc = 2) + abc;}"
assert 7 "int main() {int first; int second; return (first = 1 + 2) + (second = 3 + 4) - first;}"
assert 3 "int main() {int first; int second; return (first = 1 + 2) + (second = 3 + 4) - second;}"
assert 42 "int main() {int first; int second; int third; return (first = 1 + 2) + (second = 3 + 4) + (third = 5 + 6) + first + second + third;}"
assert 0 "int main() {int a; int b; int c; a = 1; b = 2; c = 3; return a + b - c; return a - b + c;}"
assert 2 "int main() {int a; int b; int c; a = 1; b = 2; c = 3; return a - b + c;}"
assert 21 "int main() {int first; int second; int third; first = 1 + 2; second = 3 + 4; third = 5 + 6; return first + second + third;}"
assert 2 "int main() {int a; a = 1; if(a) return 2; else return 3;}"
assert 3 "int main() {int a; a = 0; if(a) return 2; else return 3;}"
assert 2 "int main() {int a; a = 1; if(a) return 2; return 3;}"
assert 3 "int main() {int a; a = 0; if(a) return 2; return 3;}"
assert 10 "int main() {int a; a = 0; while(a < 10) a = a + 1; return a;}"
assert 20 "int main() {int a; int b; a = 0; b = 20; while(a < b) a = a + 1; return a;}"
assert 1 "int main() {int i; for(i=1;i<=10;i=i+1)return i;}"
assert 100 "int main() {int a; int i; a = 100; for(i = 0; i < 0; i = i + 1) a = a + 1; return a;}"
assert 1 "int main() {int a; int i; a = 0; for(i = 0; i < 1; i = i + 1) a = a + 1; return a;}"
assert 10 "int main() {int a; int i; a = 0; for(i = 0; i < 10; i = i + 1) a = a + 1; return a;}"
assert 45 "int main() {int a; int i; a = 0; for(i = 0; i < 10; i = i + 1) a = a + i; return a;}"
assert 45 "int main() {int sum; int i; sum = 0; i = 0; while(i < 10) { sum = sum + i; i = i+ 1; } return sum;}"
assert 1 "int main() {return f1();}"
assert 1 "int main() {int a; a = 100; return f1();}"
assert 100 "int main() {return f100();}"
assert 100 "int main() {int a; a = 1; return f100();}"
assert 31 "int main() {int a; int b; a = 10; b = 20; return a + f1() + b;}"
assert 130 "int main() {int a; int b; a = 10; b = 20; return a + f100() + b;}"
assert 11 "int main() {return inc(10);}"
assert 100 "int main() {return inc(99);}"
assert 11 "int main() {return inc(4 + 6);}"
assert 11 "int main() {return inc(1 + 2 + 3 + 4);}"
assert 11 "int main() {int a; a = 10; return inc(a);}"
assert 22 "int main() {int a; a = 10; return inc(a + 11);}"
assert 3 "int main() {return plus(1, 2);}"
assert 7 "int main() {return plus(1+2, 4);}"
assert 10 "int main() {return plus(1+2, 3+4);}"
assert 10 "int main() {return plus(plus(1,2), plus(3,4));}"
assert 10 "int main() {int a; int b; a =plus(1,2); b= plus(3,4); return plus(a, b);}"
assert 1 "int myf1() { return 1; } int main() {return myf1();}"
assert 100 "int myf100() { return 100; } int main() {return myf100();}"
assert 101 "int myf1() { return 1; } int myf100() { return 100; } int main() {return myf1() + myf100();}"
assert 100 "int my_id(int a) { return a; } int main() {return my_id(100); }"
assert 2 "int my_inc(int a) { return a+1; } int main() { return my_inc(1); }"
assert 9 "int my_inc(int a) { return a+1; } int main() { return my_inc(1) + my_inc(2) + my_inc(3); }"
assert 3 "int my_plus(int a, int b) { return a + b; } int main () { return my_plus(1, 2); }"
assert 36 "int my_plus(int a, int b, int c, int d) { return a + b + d + c; } int main () { return my_plus(1, 2, 3, 4) + my_plus(5,6,7,8); }"
assert 55 "int my_sum(int n) { int s; int i; s=0; for(i=0;i<=n;i=i+1) { s = s + i; } return s; } int main () { return my_sum(10); }"
assert 100 "int my_recur(int n) { if(n==0) { return 100; } else { return my_recur(n-1); } } int main () {return my_recur(0); }"
assert 100 "int my_recur(int n) { if(n==0) { return 100; } else { return my_recur(n-1); } } int main () {return my_recur(1); }"
assert 100 "int my_recur(int n) { if(n==0) { return 100; } else { return my_recur(n-1); } } int main () {return my_recur(2); }"
assert 1 "int my_fact(int n) { if(n==0) { return 1; } else { return n * my_fact(n-1); } } int main () {return my_fact(0); }"
assert 1 "int my_fact(int n) { if(n==0) { return 1; } else { return n * my_fact(n-1); } } int main () {return my_fact(1); }"
assert 120 "int my_fact(int n) { if(n==0) { return 1; } else { return n * my_fact(n-1); } } int main () {return my_fact(5); }"
assert 100 "int main() { int a; a = 100; return *(&a); }"
assert 100 "int main() { int a; int* b; a = 100; b = &a; return *b; }"
assert 111 "int main () {int a; int *b; int **c; int ***d; a = 111; b = &a; c = &b; d = &c; return ***d; }"
assert 100 "int main () { int a; int* b; a = 100; b = &a; return *b; }"
assert 100 "int main () { int a; int* b; b = &a; *b = 100; return *b; }"
assert 100 "int main () { int a; int* b; b = &a; *b = 100; return a; }"

# pointer test (unstable)
assert 10 "int main () { int a; int b; int c; int* p; a = 1; b = 10; c = 100; p = &b; return *p; }"
assert 100 "int main () { int a; int b; int c; int* p; a = 1; b = 10; c = 100; p = &b; return *(p+1); }"
assert 1 "int main () { int a; int b; int c; int* p; a = 1; b = 10; c = 100; p = &b; return *(p-1); }"

# array
assert 10 "int main () { int a[1]; *a = 10; return *a; }"
assert 10 "int main () { int a[3]; *a = 10; return *a; }"
assert 111 "int main () { int a[3]; *a = 10; *(a+1) = 100; *(a+2) = 1; return *a + *(a+1) + *(a+2); }"

# array indexing
assert 20 "int main () { int a[1]; *a = 20; return a[0]; }"
assert 20 "int main () { int a[1]; a[0] = 20; return a[0]; }"
assert 99 "int main () { int a[2]; a[1] = 99; return a[1]; }"
assert 55 "int main () { int a[3]; a[2] = 55; return a[2]; }"
assert 55 "int main () { int a[3]; a[2] = 55; return a[1+1]; }"
assert 55 "int main () { int a[3]; a[2] = 55; return a[1+2*3-6+1]; }"
assert 100 "int main () { int a[2]; a[0] = 1; a[1] = 99; return a[0]+a[1]; }"
assert 6 "int main () { int a[3]; a[0] = 1; a[1] = 2; a[2] = 3; return a[0]+a[1]+a[2]; }"

# global variable
assert 100 "int a; int main () { a = 111; return 100; }"
assert 100 "int a; int main () { a = 100; return a; }"
assert 123 "int a; int b; int main () { a = 100; b = 23; return a + b; }"
assert 6 "int a[3]; int main () { a[0] = 1; a[1] = 2; a[2] = 3; return a[0] + a[1] + a[2]; }"


echo OK