#!/bin/bash

# set -x

assert() {
  expected="$1"
  input="$2"

  ./fcc "$input" > /tmp/tmp.s
  riscv32-unknown-elf-gcc -o /tmp/tmp /tmp/tmp.s
  qemu-riscv32 /tmp/tmp
  actual="$?"

  if [ "$actual" = "$expected" ]; then
    echo "$input => $actual"
  else
    echo "$input => $expected expected, but got $actual"
    exit 1
  fi
}



assert 0 0
assert 100 100
assert 1 "0 + 1"
assert 5 "2 + 3"
assert 1 "3 - 2"
assert 10 "1 +2+3 - 4   + 5 + 6 - 7 + 8 -9 + 15 - 10"
assert 7 "1 + 2*3"
assert 62 "4 * 5 + 6 * 7"
assert 53 "(1 + 2) * 3 + 4 * (5 + 6)"
assert 0 "0 == 1"
assert 1 "10 == 10"
assert 1 "0 != 1"
assert 0 "10 != 10"


echo OK